stages: # Stage name (can be anything)
  - validate
  
image: python:3.11 # Docker image with Python

variables:
  BQ_CRED: $BQ_KEY_test # Get the key from GitLab Variables

validate: # Validation stage script
  stage: validate
  script:
    - python gitlab_cicd/cicd_validate.py # Run our script
  only: # Trigger condition
    refs: # Only for main branch
      - main
